# Generated by Django 4.1.7 on 2023-02-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_rename_projects_project_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
    ]
